name: Deploy on Push

on:
  push:
    branches:
      - main # Trigger action when there's a push to the 'development' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3 # This step checks out your code

      - name: Call Deployment API
        env:
          API_URL: https://deploy.path.rest/api/v1/deploy
          API_KEY: XXXXXXXXXXXXXXXXXX # Store the API key in GitHub Secrets
        run: |
          curl -X POST "$API_URL" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main", "serviceName": "backend-api "}'
